### PR TITLE
Change text on beta page for R2

### PR DESCRIPTION
**Pull request by j08lue**
Closes https://github.com/US-GHG-Center/ghgc-architecture/issues/206

- [x] Update beta page text according to specifications from our [text doc](https://docs.google.com/document/d/1iKeai-Y_219GCoRiWy5q6mUmvBHt-HmniBUSWppEgVI/edit#heading=h.m1h1jnag0efy)

## How to test

View https://deploy-preview-344--ghg-demo.netlify.app/development and compare it with the specifications.

Please note: The app version (currently `v1.0.7`) will get updated automatically, once we make the `v2.0.0` release.

### CODE REVIEW

**Review by rwyatt19 — CHANGES_REQUESTED** [review]
Thanks, Jonas! A couple of small things:

- In the page title, remove capitalization for "Continuously Improving" (change to "continuously improving")
- The version number in the first sentence in the first paragraph needs to be v2.0.0.

**Comment by rwyatt19** [comment]
Thanks @j08lue for the clear directions about how to proceed with reviewing the pull request... I don't "Github" at this level much, so I appreciate the guidance!

**Comment by j08lue** [comment]
I fixed the title as you asked, @rwyatt19. The version will be updated to 2.0.0 automatically when we make the production release.

Please review and give your formal approval above, same steps as before.

**Comment by rwyatt19** [comment]
Date will need to be changed once TEG approves portal changes and launch date is determined

**Pull request merged**
