### PR TITLE
Update ui module

### PR DESCRIPTION
**Pull request by slesaad**
## What am I changing and why

Update UI module to the latest main at commit 8804ee30025bd81cdc841e8c1d22d94d7eb4675a
- Fixes y label in time-series chart

## How to test
- Manually validated 

## ⚠️ Checks

- [x] I have confirmed that [updating the `veda-ui` submodule](https://github.com/NASA-IMPACT/veda-config-ghg/blob/main/docs/DEVELOPMENT.md#development) is needed and **only done so** if that's the case.

### CODE REVIEW

**Comment by slesaad** [comment]
@sandrahoang686 @hanbyul-here anything i need to look an eye out for with this?

**Comment by sandrahoang686** [comment]
@slesaad is this so you can pull in changes from this PR [here](https://github.com/NASA-IMPACT/veda-ui/pull/883)? I would just manually validate the deploy preview to see that no unexpected behaviors are happening, otherwise all AE changes we have been pushing should still be flagged 👍🏼

**Comment by slesaad** [comment]
@hanbyul-here i was planning to get it out today, but can wait if there's gonna be a release by friday. there's another fix in the analysis page that needs to go out soon. let me know!

**Comment by hanbyul-here** [comment]
It seems like a good time to cut a release on UI: https://github.com/NASA-IMPACT/veda-ui/pull/895 Unless we see a critical problem, let's use this v4.2

**Review by amarouane-ABDELHAK — APPROVED** [review]

**Pull request merged**
