### PR TITLE
Add video to Data Insights stories/into-us-ghg-center

### PR DESCRIPTION
**Pull request by sandrahoang686**
## Why are you creating this Pull Request?

Closes https://github.com/US-GHG-Center/ghgc-architecture/issues/198

* Adds demo video to data-insights `/stories/intro-us-ghg-center`

- [Adding Datasets or Stories](?title=Content%3A%20%3Cname%3E&expand=1&template=content.md)
- [Version Release](?title=Deploy%20vX.X.X&expand=1&template=version_release.md)
- [Other](?expand=1&template=default.md)

### CODE REVIEW

**Review by j08lue — APPROVED** [review]
Awesome, thank you. I'll go ahead and merge this atomic change.

image

**Comment by faustoperez** [comment]
Looking good @sandrahoang686 ! One minor thing, can we make the `Learn more` button use a secondary style? The two buttons are clashing a bit.

From this:

image

To this:

image

Thank you!

**Comment by j08lue** [comment]
I merged quickly yesterday before you had a chance to review, @faustoperez, so this could go right into ongoing stakeholder review.

Will otherwise wait for your sign-off. 🙏

**Comment by faustoperez** [comment]
> I merged quickly yesterday before you had a chance to review, @faustoperez, so this could go right into ongoing stakeholder review.

Super fast work everybody 🚀 , I have just a this minor comment on the button style, thanks for creating a separate ticket 🙏

**Pull request merged**
