### PR TITLE
add initial playwright suite

### PR DESCRIPTION
**Pull request by stephenkilbourn**
This add a Playwright as a possible end to end testing suite. There is a github action that will run the suite on each MR.  A developer can also run the tests by the script `yarn test:e2e`.

The suite will run the tests in three browsers:
- chromium
- firefox
- webkit

After the test run, the action will attach a report as a zip file.  That file will have an html report of the test run. In addition, any failed tests from the run will include a trace that includes network calls and screenshots to allow a developer to walk through the test in an attempt to debug the root cause of failure.

### CODE REVIEW

**Comment by stephenkilbourn** [comment]
@anayeaye - tagging you here, but I'm not sure who else should review. I can walk through the code in a call, as well.

**Comment by j08lue** [comment]
nb - currently, this PR includes a change to the VEDA UI git submodule version. That change should be removed from the PR, I guess.

**Comment by j08lue** [comment]
Thanks for moving this forwards, @stephenkilbourn!

Regarding reviews - the Dashboard team (@hanbyul-here, @sandrahoang686) have been looking after the setup of these config repos in the past and would be good to bring in for assessing this.

While I think we could consider merging this Playwright setup for a bit of real-world testing in the common weeks, I would first like for the team to get an understanding of the consequences in terms of maintenance and development overhead this may cause.

**Comment by stephenkilbourn** [comment]
> nb - currently, this PR includes a change to the VEDA UI git submodule version. That change should be removed from the PR, I guess.

good catch. reverted that in [this commit](https://github.com/NASA-IMPACT/veda-config-ghg/pull/250/commits/bdfce2f4b5c60dea57d3913c61b15085a2b59c30)

**Comment by sandrahoang686** [comment]
Same comment applies here: https://github.com/NASA-IMPACT/veda-ui/pull/835#issuecomment-1964255232

**Comment by stephenkilbourn** [comment]
closing to use work in veda-config for use with veda-deploy: https://github.com/NASA-IMPACT/veda-config/pull/363

**Pull request closed without merging**
