### PR TITLE
Add playwright qa scenarios

### PR DESCRIPTION
**Pull request by stephenkilbourn**
This addresses test scenarios mentioned in https://github.com/NASA-IMPACT/veda-ui/issues/1024

The playwright suite will be able to run through the following scenarios relying on the test data already in the `/datasets` and `/stories` directories which expands to 66 unique tests on the GHG dev branch:

1. Explore data button on dataset overview page works
2. Check the connection between Dataset Overview page to E&A layer modal
3. Check the connection between Taxonomy pills on Dataset Overview page
4. Check the connection between Taxonomy pills on Dataset Overview page
5. E&A layer selection modal - excluded (flagged by disableExplore property) datasets are omitted
6. Data stories look as expected
7. Data catalog looks as expected
8. Nav links in top nav and footer work
9. Learn and About pages look as expected
10. Contact Us buttons work
11. External links open in a new tab

"look as expected" was vague, so for now it is testing that no javascript errors appear that would break the page.  Other assertions could be made.

I've attached the html of a test run report to illustrate what a successful run would look like. 

[index.html.zip](https://github.com/user-attachments/files/16567244/index.html.zip)

### CODE REVIEW

**Review by dzole0311 — APPROVED** [review]
Thanks so much for adding these, @stephenkilbourn, looks great! This gives us a good foundation that will make it easy to build upon and add more scenarios.

I noticed the scenarios are currently commented out in the .github workflow. Are there any blockers to enable them again in this PR before merging it? Like that we could already test the whole pipeline with the next GHG Center version bump.

Also, what are your thoughts on migrating some of these scenarios to the `veda-ui` repo? We have mocked data there used for development and theoretically we could already run the tests earlier as part of the UI release process before they reach the instances.

**Comment by stephenkilbourn** [comment]
I had disabled the workflow during the last GHG deploy because running yarn start was taking over 3 minutes to start the server and delaying a passing build.  I'll re-enable it here and look into some caching to see if there's a way to improve that.  

It would also be my preference to run tests if possible in the UI.  catching issues as early as possible makes debugging easier.  I'll look into if I see a clear way to delineate without duplicating code.

**Comment by stephenkilbourn** [comment]
@slesaad - I see the test failed because the Hub link in the header has `target="blank"` while other external links are set as `target="_blank"` (including the Hub link in the footer.  Technically, the `target="blank"` [will work,](https://css-tricks.com/targetblank/) but I'm guessing it was an error to change this in veda-ui.

**Comment by slesaad** [comment]
@stephenkilbourn thanks so much for updating the tests! so quick too! 🥳

**Review by slesaad — APPROVED** [review]

**Pull request merged**
