### PR TITLE
Remove subtitle in homepage hero

### PR DESCRIPTION
**Pull request by j08lue**
- [x] Remove subtitle in homepage hero
- [x] Remove other occurrences https://github.com/search?q=repo%3AUS-GHG-Center%2Fveda-config-ghg%20uniting%20data%20technology&type=code\
- [x] Fix Playwright test

### CODE REVIEW

**Comment by j08lue** [comment]
@Jeanne-le-Roux, on the [about](https://earth.gov/ghgcenter/about) page, should there be another subtile? Or none?

image

**Comment by Jeanne-le-Roux** [comment]
@j08lue no subtitle for that page. 

I _think_ that's the only other place the tagline shows up - but need to double check.

**Comment by j08lue** [comment]
image

🙄

**Comment by j08lue** [comment]
Gone.

image

**Comment by j08lue** [comment]
Is this acceptable, @Jeanne-le-Roux? Or should we ask for a quick design review to adjust the whitespace now that there is no subtitle? That might require overriding the about page header, though. 🙄

**Review by Jeanne-le-Roux — APPROVED** [review]

**Comment by j08lue** [comment]
Great! You want this change to be in the next release, right? If so, please merge this PR, @Jeanne-le-Roux, so it gets into staging.

**Comment by Jeanne-le-Roux** [comment]
@j08lue thanks for jumping in and taking care of this!

**Pull request merged**
